name: Deploy .NET API to Azure (PROD)

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'WebAppAstralisApiDotnetProdCode'
  DOTNET_VERSION: '8.x'
  PROJECT_PATH: 'Astralis_API/Astralis_API.csproj'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Installation de .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # 3. Compilation et Publication
      - name: Build and Publish
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ./publish

      # 4. Déploiement sur Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          package: ./publish